site_name: Textual
site_url: https://textual.textualize.io/
repo_url: https://github.com/textualize/textual/
edit_uri: edit/css/docs/

nav:
  - Introduction:
    - "index.md"
    - "getting_started.md"
  - "tutorial.md"
  - Guide:
    - "guide/index.md"
    - "guide/devtools.md"
    - "guide/app.md"
    - "guide/styles.md"
    - "guide/CSS.md"
    - "guide/queries.md"
    - "guide/layout.md"
    - "guide/events.md"
    - "guide/input.md"
    - "guide/actions.md"
    - "guide/reactivity.md"
    - "guide/widgets.md"
    - "guide/animation.md"
    - "guide/screens.md"
  - "roadmap.md"
  - Events:
    - "events/index.md"
    - "events/blur.md"
    - "events/descendant_blur.md"
    - "events/descendant_focus.md"
    - "events/enter.md"
    - "events/focus.md"
    - "events/hide.md"
    - "events/key.md"
    - "events/leave.md"
    - "events/load.md"
    - "events/mount.md"
    - "events/mouse_capture.md"
    - "events/click.md"
    - "events/mouse_down.md"
    - "events/mouse_move.md"
    - "events/mouse_release.md"
    - "events/mouse_scroll_down.md"
    - "events/mouse_scroll_up.md"
    - "events/mouse_up.md"
    - "events/paste.md"
    - "events/resize.md"
    - "events/screen_resume.md"
    - "events/screen_suspend.md"
    - "events/show.md"
  - Styles:
    - "styles/index.md"
    - "styles/align.md"
    - "styles/background.md"
    - "styles/border.md"
    - "styles/box_sizing.md"
    - "styles/color.md"
    - "styles/content_align.md"
    - "styles/display.md"
    - "styles/dock.md"
    - "styles/grid.md"
    - "styles/height.md"
    - "styles/layer.md"
    - "styles/layers.md"
    - "styles/layout.md"
    - "styles/links.md"
    - "styles/margin.md"
    - "styles/max_height.md"
    - "styles/max_width.md"
    - "styles/min_height.md"
    - "styles/min_width.md"
    - "styles/offset.md"
    - "styles/opacity.md"
    - "styles/outline.md"
    - "styles/overflow.md"
    - "styles/padding.md"
    - "styles/scrollbar.md"
    - "styles/scrollbar_gutter.md"
    - "styles/scrollbar_size.md"
    - "styles/text_align.md"
    - "styles/text_style.md"
    - "styles/text_opacity.md"
    - "styles/tint.md"
    - "styles/visibility.md"
    - "styles/width.md"
  - Widgets:
    - "widgets/index.md"
    - "widgets/button.md"
    - "widgets/checkbox.md"
    - "widgets/data_table.md"
    - "widgets/footer.md"
    - "widgets/header.md"
    - "widgets/input.md"
    - "widgets/static.md"
    - "widgets/tree_control.md"
  - Reference:
    - "reference/app.md"
    - "reference/button.md"
    - "reference/color.md"
    - "reference/containers.md"
    - "reference/dom_node.md"
    - "reference/events.md"
    - "reference/footer.md"
    - "reference/geometry.md"
    - "reference/header.md"
    - "reference/index.md"
    - "reference/message_pump.md"
    - "reference/message.md"
    - "reference/query.md"
    - "reference/reactive.md"
    - "reference/screen.md"
    - "reference/static.md"
    - "reference/timer.md"
    - "reference/widget.md"
  - "help.md"



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - admonition
  - def_list
  - meta

  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg
        - name: rich
          class: rich
          format: !!python/name:textual._doc.rich
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - markdown.extensions.attr_list

theme:
  name: material
  custom_dir: docs/custom_theme
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - content.code.annotate
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:

- search:
- autorefs:
- mkdocstrings:
    default_handler: python
    handlers:
        python:
          options:
            show_source: false
            filters:
              - "!^_"
              - "^__init__$"
              - "!^can_replace$"

    watch:
      - src/textual


extra_css:
  - stylesheets/custom.css
