site_name: Textual
site_url: https://www.textualize.io/

nav:
  - "index.md"
  - "introduction.md"
  - Guide:
    - "guide/guide.md"
  - "actions.md"
  - Events:
    - "events/mount.md"
    - "events/resize.md"
  - Styles:
    - "styles/background.md"
    - "styles/border.md"
    - "styles/box_sizing.md"
    - "styles/color.md"
    - "styles/content_align.md"
    - "styles/display.md"
    - "styles/min_height.md"
    - "styles/max_height.md"
    - "styles/min_width.md"
    - "styles/max_width.md"
    - "styles/height.md"
    - "styles/margin.md"
    - "styles/offset.md"
    - "styles/outline.md"
    - "styles/overflow.md"
    - "styles/padding.md"
    - "styles/scrollbar.md"
    - "styles/scrollbar_size.md"
    - "styles/text_style.md"
    - "styles/tint.md"
    - "styles/visibility.md"
    - "styles/width.md"
  - Widgets: "/widgets/"
  - Reference:
    - "reference/app.md"
    - "reference/events.md"
    - "reference/geometry.md"
    - "reference/widget.md"

markdown_extensions:
  - admonition
  - def_list
  - meta
  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - markdown.extensions.attr_list

theme:
  name: material
  custom_dir: custom_theme
  # features:
  #   - navigation.tabs
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:

- search:
- mkdocstrings:
    default_handler: python
    handlers:
        python:
          rendering:
            show_source: false
          selection:
            filters:
              - "!^_"
              - "^__init__$"
              - "!^can_replace$"

    watch:
      - src/textual


extra_css:
  - stylesheets/custom.css
