site_name: Textual
site_url: https://textual.textualize.io/
repo_url: https://github.com/textualize/textual/
edit_uri: edit/main/docs/

nav:
  - Introduction:
    - "index.md"
    - "getting_started.md"
    - "help.md"
  - "tutorial.md"
  - Guide:
    - "guide/index.md"
    - "guide/devtools.md"
    - "guide/app.md"
    - "guide/styles.md"
    - "guide/CSS.md"
    - "guide/design.md"
    - "guide/queries.md"
    - "guide/layout.md"
    - "guide/events.md"
    - "guide/input.md"
    - "guide/actions.md"
    - "guide/reactivity.md"
    - "guide/widgets.md"
    - "guide/animation.md"
    - "guide/screens.md"
  - "roadmap.md"
  - Reference:
    - "reference/index.md"
    - CSS Types:
      - "css_types/index.md"
      - "css_types/border.md"
      - "css_types/color.md"
      - "css_types/horizontal.md"
      - "css_types/integer.md"
      - "css_types/name.md"
      - "css_types/number.md"
      - "css_types/overflow.md"
      - "css_types/percentage.md"
      - "css_types/scalar.md"
      - "css_types/text_align.md"
      - "css_types/text_style.md"
      - "css_types/vertical.md"
    - Events:
      - "events/index.md"
      - "events/blur.md"
      - "events/descendant_blur.md"
      - "events/descendant_focus.md"
      - "events/enter.md"
      - "events/focus.md"
      - "events/hide.md"
      - "events/key.md"
      - "events/leave.md"
      - "events/load.md"
      - "events/mount.md"
      - "events/mouse_capture.md"
      - "events/click.md"
      - "events/mouse_down.md"
      - "events/mouse_move.md"
      - "events/mouse_release.md"
      - "events/mouse_scroll_down.md"
      - "events/mouse_scroll_up.md"
      - "events/mouse_up.md"
      - "events/paste.md"
      - "events/resize.md"
      - "events/screen_resume.md"
      - "events/screen_suspend.md"
      - "events/show.md"
    - Styles:
      - "styles/index.md"
      - "styles/align.md"
      - "styles/background.md"
      - "styles/border.md"
      - "styles/box_sizing.md"
      - "styles/color.md"
      - "styles/content_align.md"
      - "styles/display.md"
      - "styles/dock.md"
      - Grid:
        - "styles/grid/index.md"
        - "styles/grid/column_span.md"
        - "styles/grid/grid_columns.md"
        - "styles/grid/grid_gutter.md"
        - "styles/grid/grid_rows.md"
        - "styles/grid/grid_size.md"
        - "styles/grid/row_span.md"
      - "styles/height.md"
      - "styles/layer.md"
      - "styles/layers.md"
      - "styles/layout.md"
      - Links:
        - "styles/links/index.md"
        - "styles/links/link_background.md"
        - "styles/links/link_color.md"
        - "styles/links/link_hover_background.md"
        - "styles/links/link_hover_color.md"
        - "styles/links/link_hover_style.md"
        - "styles/links/link_style.md"
      - "styles/margin.md"
      - "styles/max_height.md"
      - "styles/max_width.md"
      - "styles/min_height.md"
      - "styles/min_width.md"
      - "styles/offset.md"
      - "styles/opacity.md"
      - "styles/outline.md"
      - "styles/overflow.md"
      - "styles/padding.md"
      - Scrollbar colors:
        - "styles/scrollbar_colors/index.md"
        - "styles/scrollbar_colors/scrollbar_background.md"
        - "styles/scrollbar_colors/scrollbar_background_active.md"
        - "styles/scrollbar_colors/scrollbar_background_hover.md"
        - "styles/scrollbar_colors/scrollbar_color.md"
        - "styles/scrollbar_colors/scrollbar_color_active.md"
        - "styles/scrollbar_colors/scrollbar_color_hover.md"
        - "styles/scrollbar_colors/scrollbar_corner_color.md"
      - "styles/scrollbar_gutter.md"
      - "styles/scrollbar_size.md"
      - "styles/text_align.md"
      - "styles/text_opacity.md"
      - "styles/text_style.md"
      - "styles/tint.md"
      - "styles/visibility.md"
      - "styles/width.md"
    - Widgets:
      - "widgets/button.md"
      - "widgets/checkbox.md"
      - "widgets/data_table.md"
      - "widgets/text_log.md"
      - "widgets/directory_tree.md"
      - "widgets/footer.md"
      - "widgets/header.md"
      - "widgets/index.md"
      - "widgets/input.md"
      - "widgets/label.md"
      - "widgets/list_view.md"
      - "widgets/list_item.md"
      - "widgets/placeholder.md"
      - "widgets/static.md"
      - "widgets/tree.md"
  - API:
    - "api/index.md"
    - "api/app.md"
    - "api/binding.md"
    - "api/button.md"
    - "api/checkbox.md"
    - "api/color.md"
    - "api/containers.md"
    - "api/coordinate.md"
    - "api/data_table.md"
    - "api/directory_tree.md"
    - "api/dom_node.md"
    - "api/events.md"
    - "api/footer.md"
    - "api/geometry.md"
    - "api/header.md"
    - "api/input.md"
    - "api/label.md"
    - "api/list_view.md"
    - "api/list_item.md"
    - "api/message_pump.md"
    - "api/message.md"
    - "api/pilot.md"
    - "api/placeholder.md"
    - "api/query.md"
    - "api/reactive.md"
    - "api/screen.md"
    - "api/static.md"
    - "api/text_log.md"
    - "api/timer.md"
    - "api/tree.md"
    - "api/tree_node.md"
    - "api/walk.md"
    - "api/widget.md"
  - "Blog":
    - blog/index.md



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - admonition
  - def_list
  - meta

  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg
        - name: rich
          class: rich
          format: !!python/name:textual._doc.rich
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - markdown.extensions.attr_list

theme:
  name: material
  custom_dir: docs/custom_theme
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.footer
    - content.code.annotate
    - content.code.copy
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:

- blog:
- rss:
    match_path: blog/posts/.*
    date_from_meta:
      as_creation: date
    categories:
      - categories
      - release
      - tags
- search:
- autorefs:
- mkdocstrings:
    default_handler: python
    handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_source: false
            filters:
              - "!^_"
              - "^__init__$"
              - "!^can_replace$"

    watch:
      - src/textual


extra_css:
  - stylesheets/custom.css


extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/textualizeio
      name: textualizeio on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/textualize/textual/
      name: Textual on Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Enf6Z3qhVr
      name: Textual Discord server
copyright: Copyright &copy; Textualize, Inc
